name: 39digits
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5079
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#366da2'
    - '#daf3fa'
    - '#99bed4'
    - '#a98086'
  brandStrength: 0.5625
  lightness: 0.27156350389122963
  saturation: 0.37919455161318183
  rhythmicContrast: 0.8484552600421011
purpose: []
